#!/bin/bash
sleep 10

##################
wifi () {
rm /tmp/con-my 
sleep 1

cd /usr/share/con-auto ; ./wifi-conect\ ;

for (( ; ; ))
do

next1=$( cat /tmp/con-my | wc -l )
if [ $next1 -eq 1 ]
then 


break
else
sleep 5
fi 

done
}
###################












for (( ;  ; ))
do 

wifi1=$(iwconfig wlan1 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g')
if [ "$wifi1" != "off/any" ]
then

status1=$( cat /usr/share/con-auto/wpalog | wc -l )

sleep 5
status2=$( cat /usr/share/con-auto/wpalog | wc -l )
if [ $status1 == $status2 ]
then
sleep 1
else
lock2=$( cd /tmp ; ls | grep lock2 | wc -l )
if [ $lock2 -eq 0 ]
then 
echo 1 > /tmp/lock1
rm /tmp/con-my 
killall tor
sleep 1
killall wifi-conect
killall wpa_supplicant 
sleep 1

wifi
rm /tmp/lock1

sleep 5
else
sleep 1
fi
fi
else
sleep 1

fi
done 
