#!/bin/bash
service apache2 start

for (( ; ; ))
do
wifi=$( iwconfig  wlan1 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g' )
ip=$( ifconfig wlan1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}' )
echo "<html><body><h1>RASBERY PI STATUS PANEL</h1>
<h3>STATUS:<span style="color:#00FF00"> ACTIVE </h3>
<h3>WIFI:<span style="color:#0000FF"> $wifi </h3>
<h3>SUBNET IP:<span style="color:#0000FF"> $ip </h3>" > /var/www/index.html
sleep 1m
done