#!/bin/bash

sleep 10
rm /usr/share/con-auto/wpalog
cat /etc/wpa_supplicant.conf > /etc/wpa_supplicant-tmp.conf
rtimes1=0
for (( ; ; ))
do

if [ "$rtimes1" -gt 1 ]
then
cat /etc/wpa_supplicant.conf > /etc/wpa_supplicant-tmp.conf
fi
sleep 2

killall NetworkManager
 killall wpa_supplicant 
 killall wpa_supplicant
 killall dhclient 
killall dhclient 

killall wpa_supplicant 
killall wpa_supplicant 
ip link set wlan1 up
ifconfig wlan1 up
sleep 2

wpa_supplicant    -D  wext -i wlan1 -f /usr/share/con-auto/wpalog -c /etc/wpa_supplicant-tmp.conf  &  for (( ; ; )) 
do 
sleep 30

connect=$( iwconfig wlan1 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g' ) 
echo $connect
sleep 1

if [ $connect != "off/any" ]
then

sleep 5
dhclient wlan1

sleep 2

break
else
sleep 1
fi
done
ping -c 1 173.194.116.239 &&  connect1=0 || connect1=1  
if [ "$connect1" -eq 0 ]
then
echo 1 > /tmp/con-my
date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"


sleep 10
date
echo 1

break



else

 name1=$( iwconfig wlan1 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g') 
 link1=$(cat /etc/wpa_supplicant-tmp.conf | grep -w "$name1") 
cat  /etc/wpa_supplicant-tmp.conf | grep -v "$link1"  > /etc/wpa_supplicant-tmp2.conf ; mv /etc/wpa_supplicant-tmp2.conf  /etc/wpa_supplicant-tmp.conf
rtimes1=$((rtimes1 + 1 ))

killall wpa_supplicant 


fi

done